---
client_id : ... # retrieve from the Azure App Registration page
tenant_id : ... # retrieve from the Azure App Registration page
recipient_email : ... # email to notify when vcs is down
scopes : # Should not be changed
  - Calendars.ReadWrite
  - Mail.Send 
  - https://graph.microsoft.com/offline_access
  - User.Read
group_name : ...  # LDAP group
shared_calendar_name: ... 
category_name: "Vacation"
category_color: "preset0"
days_out: 30 # indicates the stretch of time (in days) that the program will update on the shared calendar relative to present day
update_interval : 900 # update_interval indicates how often the program run in seconds
email_list_update_interval: 20
start_of_work_day: 480 # 60 * 8
end_of_work_day: 1020 # 60 * 17
start_of_lunch: 720 # 60 * 12
end_of_lunch: 780 # 60 * 13
duration: 180 # 60 * 3